### PR TITLE
Metamask as wallet options

### PR DESCRIPTION
**Pull request by paulfears**
### Description

Added a metamask client as a wallet options.

### Checklist

> _Please, make sure to comply with the checklist below before expecting review_

- [ ] Code compiles correctly
- [ ] Created tests which fail without the change (if possible)
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by drichar** [comment]
Hi @paulfears, thank you for resubmitting your pull request. There are TypeScript errors preventing CI checks from passing (see below). Also, another pull request was just merged that introduced some minor conflicts on your branch, which should be pretty easy to fix.

I edited the pull request description to restore the template we use for contributions. Please run `yarn check-types` locally before pushing your commit(s) to be sure there are no TypeScript errors in your changes.

If you have any questions let me know. Thanks!

**Comment by drichar** [comment]
@paulfears Any update(s) on this?

**Comment by SilentRhetoric** [comment]
Hey @paulfears, may I ask if this is something you are planning to complete?

**Comment by drichar** [comment]
Closing this due to inactivity. Please open a new pull request @paulfears if/when you're ready to revisit this feature.

**Pull request closed without merging**
