### PR TITLE
feat: integrate daffiwallet connect

### PR DESCRIPTION
**Pull request by techtycoon-haroon**
### Description

> Integrated DaffiWallet Mobile App

### Checklist

> _Please, make sure to comply with the checklist below before expecting review_

- [ ] Code compiles correctly
- [ ] Created tests which fail without the change (if possible)
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by drichar** [comment]
Can you publish the source code for @daffiwallet/connect? The Repository link on https://www.npmjs.com/package/@daffiwallet/connect points to an empty repository.

**Comment by techtycoon-haroon** [comment]
We have updated code to git repo.

**Review by ThomasLarsen12 — APPROVED** [review]
Ok

**Review by faiqnadeem — APPROVED** [review]

**Comment by MBernierRD** [comment]
Is there any indication of the time required for the review?

**Review by drichar — APPROVED** [review]

**Comment by drichar** [comment]
The package.json file was updated to include `@daffiwallet/connect` but the lockfile `yarn.lock` was not updated. I'll merge this to `release-1.3.0` branch and take care of that before merging to `main`.

**Comment by MBernierRD** [comment]
Thanks doug

**Comment by drichar** [comment]
@MBernierRD @techtycoon-haroon https://github.com/TxnLab/use-wallet/releases/tag/v1.3.0-alpha.0 is published to npm, after some QA the full release should go out tomorrow!

**Pull request merged**
